### ISSUE TITLE
Could not dowload interproscan 1 computed checksum did NOT match

### ISSUE THREAD

**Issue by jhcuarta** [flass/pantagruel#48] opened 2022-04-26 21:14 UTC
Hi 
While trying to install interproscan i came across this issue

md5sum: WARNING: 1 computed checksum did NOT match
ERROR: Could not dowload interproscan-5.55-88.0-64-bit.tar.gz

Any help it would be appraciate it

**Comment by flass** [comment] 2022-04-27 09:04
Hi,
this looks like a network issue preventing the complete and integral download of the latest interproscan release - this is a very big file due to the underlying database and therefore can easily fail with a fragile network. I recommend downloading this by hand and then indicating to Pantagruel where to find the InterProScan executable using the `--path_to_interproscan` option.
I'll close this issue for now but please re-open if the problem is not solved this way.
Best wishes,
Florent

**Closed as completed by flass** 2022-04-27 09:04 UTC
Labels: interproscan
